create type public.account_role as enum ('user', 'admin');
create type public.user_profile_role as enum (
  'produtor',
  'gestor',
  'estudante',
  'consultor',
  'administrador'
);
create type public.user_sex as enum (
  'feminino',
  'masculino',
  'outro',
  'nao_informar'
);
create type public.financial_entry_type as enum (
  'receita',
  'custo_producao',
  'custo_fixo',
  'custo_variavel',
  'despesa_administrativa',
  'imposto',
  'deducao'
);
create type public.financial_settlement_status as enum (
  'liquidado',
  'pendente'
);

create table public.users (
  id integer generated by default as identity primary key,
  "openId" varchar(64) not null,
  name text,
  email varchar(320),
  "loginMethod" varchar(64),
  role public.account_role not null default 'user',
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  "lastSignedIn" timestamptz not null default now()
);

create unique index users_open_id_unique on public.users ("openId");

create table public."userProfiles" (
  id integer generated by default as identity primary key,
  "userId" integer not null unique references public.users(id) on delete cascade,
  "profileRole" public.user_profile_role not null,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create index user_profiles_role_idx
  on public."userProfiles" ("profileRole");

create table public.usuarios (
  cpf varchar(11) primary key,
  name varchar(160) not null,
  sex public.user_sex not null default 'nao_informar',
  "createdById" integer not null references public.users(id) on delete cascade,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create index usuarios_creator_idx on public.usuarios ("createdById");

create table public."ruralProperties" (
  id integer generated by default as identity primary key,
  "ownerId" integer not null references public.users(id) on delete cascade,
  name varchar(140) not null,
  municipality varchar(100),
  state varchar(2),
  "totalArea" numeric(12, 2),
  "mainActivity" varchar(120),
  description text,
  "isActive" boolean not null default true,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create index rural_properties_owner_idx
  on public."ruralProperties" ("ownerId");

create table public."usuarioPropriedade" (
  "userCpf" varchar(11) not null references public.usuarios(cpf) on delete cascade,
  "propertyId" integer not null references public."ruralProperties"(id) on delete cascade,
  "createdAt" timestamptz not null default now(),
  constraint usuario_propriedade_pk primary key ("userCpf", "propertyId")
);

create index usuario_propriedade_property_idx
  on public."usuarioPropriedade" ("propertyId");

create table public."financialEntries" (
  id integer generated by default as identity primary key,
  "propertyId" integer not null references public."ruralProperties"(id) on delete cascade,
  "createdById" integer not null references public.users(id) on delete cascade,
  "entryType" public.financial_entry_type not null,
  category varchar(100) not null,
  activity varchar(120) not null default 'Não informada',
  description text not null,
  "occurredOn" date not null,
  "dueOn" date,
  "settlementStatus" public.financial_settlement_status not null default 'liquidado',
  "settledOn" date,
  amount numeric(14, 2) not null,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create index financial_entries_property_date_idx
  on public."financialEntries" ("propertyId", "occurredOn");
create index financial_entries_property_activity_date_idx
  on public."financialEntries" ("propertyId", activity, "occurredOn");
create index financial_entries_property_status_idx
  on public."financialEntries" ("propertyId", "settlementStatus");
create index financial_entries_creator_idx
  on public."financialEntries" ("createdById");

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new."updatedAt" = now();
  return new;
end;
$$;

create trigger users_set_updated_at
before update on public.users
for each row execute function public.set_updated_at();

create trigger user_profiles_set_updated_at
before update on public."userProfiles"
for each row execute function public.set_updated_at();

create trigger usuarios_set_updated_at
before update on public.usuarios
for each row execute function public.set_updated_at();

create trigger rural_properties_set_updated_at
before update on public."ruralProperties"
for each row execute function public.set_updated_at();

create trigger financial_entries_set_updated_at
before update on public."financialEntries"
for each row execute function public.set_updated_at();

alter table public.users enable row level security;
alter table public."userProfiles" enable row level security;
alter table public.usuarios enable row level security;
alter table public."ruralProperties" enable row level security;
alter table public."usuarioPropriedade" enable row level security;
alter table public."financialEntries" enable row level security;

revoke all on table public.users from anon, authenticated;
revoke all on table public."userProfiles" from anon, authenticated;
revoke all on table public.usuarios from anon, authenticated;
revoke all on table public."ruralProperties" from anon, authenticated;
revoke all on table public."usuarioPropriedade" from anon, authenticated;
revoke all on table public."financialEntries" from anon, authenticated;
